# Guarneri-style device YAML configuration

apsbits.utils.sim_creator.predefined_device:
- { creator: ophyd.sim.motor, name: sim_motor }
- { creator: ophyd.sim.noisy_det, name: sim_det }

apstools.devices.SimulatedApsPssShutterWithStatus:
- name: shutter
  labels: [ "shutters", "baseline" ]

bm11_b.devices.slew_scan_devices.SlewDevice:
- name: slew
  prefix: "11bmb:"
  labels: [ "slew" ]

bm11_b.devices.slew_scan_devices.SpyLambda:
- name: spy_lambda
  prefix: "11bmbLambda:"
  labels: [ "slew" ]

## THIS ARE EXAMPLES OF OTHER DEVICES THAT YOU CAN USE
# ophyd.Signal:
# - name: test
#   value: 50.7
# - name: t2
#   value: 2

# apstools.synApps.Optics2Slit2D_HV:
# - name: slit1
#   prefix: ioc:Slit1
#   labels: ["slits", "baseline"]

# hkl.SimulatedE4CV:
# - name: sim4c
#   prefix: ""
#   labels: ["diffractometer"]

ophyd.scaler.ScalerCH:
- name: scaler1
  prefix: 11bmb:scaler1
  labels: ["scalers", "detectors"]

ophyd.EpicsMotor:
- {name: tth, prefix: 11bmb:m28, labels: ["motor"]}
# - {name: m2, prefix: gp:m2, labels: ["motor"]}
# - {name: m3, prefix: gp:m3, labels: ["motor"]}
# - {name: m4, prefix: gp:m4, labels: ["motor"]}

ophyd.EpicsSignal:
- {name: spinner, read_pv: 11bmb:DAC2_6}

# apstools.devices.ad_creator:
#   - name: adsimdet
#     prefix: "ad:"
#     labels: ["area_detector", "detectors"]
#     plugins:
#       - cam:
#           class: apstools.devices.SimDetectorCam_V34
#       - image
#       - pva
#       - hdf1:
#           class: apstools.devices.AD_EpicsFileNameHDF5Plugin
#           read_path_template: "/path/to/bluesky/tmp/"
#           write_path_template: "/path/to/ioc/tmp/"
#       - roi1
#       - stats1
